### ISSUE TITLE
Add auctions

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#10]
We have to add auctions to FlatFindr:

I added basic functionality for viewing bids and bidding on ads. What still has to be done is:

**Priority (25 October, 23:55):**
- [x] Auctions should have a time limit. (@daveb17117)
- [x] The user with the highest bid gets a message stating he won the auction when the auction ends. (@daveb17117)
- [x] The user who started the auction should get a message containing the contact details of the winner (highest bidder) once the auction has ended. (@daveb17117)
- [x] Users who bid in the auction get a message once someone overbids them. (@daveb17117)
- [x] The price of the house should be = highest bid so far (@jounus)
- [x] You should only be able to bid when you bid more than the highest bid so far (@jounus)
- [x] Make a show all bids, hide all bids button to show bid history (like in advanced search from last week) And order the bids by timestamp. (@jounus)

**Lower Priority:**
- [ ] – If your auction ended unsuccessfully, you should get the option to put the auction anew on FlatFindr (without having to go through all the trouble to state the parameters of your room etc. again). This probably has secondary priority now.
- [ ] Any path exposed by a controller should have a test. (https://github.com/scg-unibe-ch/ese2016/wiki/Architectural-Guidelines)

Notes: There is no 'instant-buy' option. The highest bidder wins at end of auction.

**Comment by jounus** [comment]
You can now see bids and make bids for an ad (very basic functionality)

What still has to be done:
- [ ] Make the price of the house = highest bid offer
- [ ] Make it so you are only able to bid higher than the highest offer
- [ ] Show all bids when you click button (show all bids), like in advanced search. 
- [ ] Sort the bids by timestamp.
- [ ] Make the auction end at a certain time. When it ends bidding should be closed, and the winner and the owner notified.

**Comment by dombriner** [comment]
Moved remaining issues to #19
