### ISSUE TITLE
Adjust search and ads to auctions, new properties and removed renting

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#11]
We have to adjust the search to the newly added properties (houses, apartments), the addition of auctions and the removal of renting and rooms:
– Users are not able to search for rooms. They are able to search for houses, apartments and studios.
– Users are not able to put in ads for rooms, but for houses, apartments and studios.
– Search parameters should vary depending on for what you search. 'Roommates', 'WiFi', 'move out' (date) and 'CableTV' can be removed. 'Furnitured' is only available for studios. Houses should have nearly no restriction (e.g. animals are always allowed in your own house). New search parameter: #rooms.
This should be right after altering the properties #12 .

**Comment by jounus** [comment]
Merged with another issue because it has to be done at the same time.
