### ISSUE TITLE
Change the design of FlatFindr

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#15]
The customer wants us to change the design of FlatFindr. This consists of shifting things around to a large part.

**Hight Priority (01.11.2016 23:55)**
- [ ] Make several sketches for a new designed FlatFindr.
- [ ] Come up with ideas to personalize the homepage for logged-in users (add things important to the user: newest messages, newest ads, newest ads corresponding the search alert, etc.).
- [ ]  Change the design of all pages (shift some things around). Just the very basics until our next meeting. (@jounus)
- [ ]  Change the functions on the homepage (maybe add search on the right or so…). Just very basic for now, until our next meeting. (@jounus)

**Low Priority** (after 02.11.2016)
- [ ] change the design to the one the customer approved

**Comment by jounus** [comment]
We will talk about this with our customer on November 2.
