### ISSUE TITLE
Design: Mobile devices, consistency

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#28]
**High Priority (15.11.23:55)**

_Mobile devices_
- [ ] Make all the pages look appropriately on mobile devices (e.g. so that scroll bars are added when needed, images don't feel too big, etc.).

_Consistency_
- [ ] Search for inconsistencies throughout the design and fix them.
- [ ] If a form is used on multiple pages, it should look the same on all pages (e.g. search form on searchAd.jsp and results.jsp).

_Search_
- [x] Make the advanced search option more visible

**Comment by jounus** [comment]
The pages are mostly consistent, just a few minor things.
