### ISSUE TITLE
Bug hunting task

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#31]
**High Priority (15.11.16 23:55)**

- [x] Find at least _3 bugs_ in the project of team 1 and report them using the _issue tracker_ of the project _of team 1_.

NOTE:
This is _not_ the full task.
Read the complete description and full task on https://github.com/scg-unibe-ch/ese2016/wiki/Task4:-Crash-your-opponents.

**Comment by jounus** [comment]
Bug #1: Go to Login page => Login as hans@unibe.ch => Go to the messages page => Error: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by jounus** [comment]
Bug #2: Login, go to page http://localhost:8080/ad?id=12. Then enter a string, for example "abc" in the bid box and click bid => TADAAA => org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NumberFormatException: For input string: ""

**Comment by jounus** [comment]
Bug #3: Login => go to addescription page => click edit ad => submit the edit ad form => WOHHOO => org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
