### ISSUE TITLE
Polish our product

### ISSUE THREAD

**Issue by dombriner** [scg-unibe-ch/ese2016-team7#49]
There are various things we can do to polish our product:

- [ ] Test the whole system interactively, try to break everything and thus find bugs. Document the bugs as an issue and ideally write a test for it.

- [ ] Check the whole system for browser compatability issues.

- [ ] Check whether we've really met all the [requirements](https://github.com/scg-unibe-ch/ese2016/wiki/Project-Description).
- [ ] Check for forgotten features/requirements in the SRS

**Comment by jounus** [comment]
We added all the issues required for this, thus closing this issue.
