### ISSUE TITLE
Update SRS and Add New Issues.

### ISSUE THREAD

**Issue by jounus** [scg-unibe-ch/ese2016-team7#8]
Add all new issues discussed with the customer to the issue tracker and update the SRS with the new requirements. By Thursday evening please, thank you! :)

(Some things in the SRS might be a bit outdated now, like for example actor characteristics. We can update those sometime too...)

**Comment by dombriner** [comment]
I updated added the issues in our issue tracker which are important for the next week. I will add issues, specifically on premium ads and provisions, by tomorrow evening.
Feel free to edit the issues ;)

**Comment by dombriner** [comment]
I think I added all issues now. Feel free to have a look and correct/edit the issues ;)
